### ISSUE TITLE
[BUG] Unable to extract version info error

### ISSUE THREAD

**Issue by alexvolchetsky** [brandedoutcast/publish-nuget#38]
**Description**
Recently started receiving errors during running of action.
It says that it can't find version info.
Noticed that in [2.5.3](https://github.com/brandedoutcast/publish-nuget/releases/tag/v2.5.3) release VERSION_REGEX were changed to `^<Version>(.*)<\/Version>$` which doesn't ignore whitespaces in the beginning of the line

**Failed Action Log URL**
https://github.com/alexvolchetsky/yandex.alice.sdk/runs/864428591?check_suite_focus=true

**To Reproduce**
Test of `^<Version>(.*)<\/Version>$` on content of my .cspoj file:
https://regex101.com/r/ZpzZkk/3/
Can't match anything

**Expected Behavior**
Test of `^\s*<Version>(.*)<\/Version>$` on content of my .cspoj file:
https://regex101.com/r/ZpzZkk/2/
Matches version info

The same regex works if set VERSION_REGEX explicitly. For instance:
```
- name: publish on version change
    id: publish_nuget
    uses: rohith/publish-nuget@v2
    with:        
      PROJECT_FILE_PATH: ./src/Yandex.Alice.Sdk/Yandex.Alice.Sdk.csproj
      NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      INCLUDE_SYMBOLS: true
      VERSION_REGEX: ^\s*<Version>(.*)<\/Version>$
```

**Environment:**
 - Platform: Ubuntu
 - Action Version: v2.5.3
