### ISSUE TITLE
[FEATURE] Multiple Nuget Deploy, 1 Step

### ISSUE THREAD

**Issue by houseofcat** [brandedoutcast/publish-nuget#41]
Straightforward, would rather create a step that I supply a directory and we just recursively find all .CSPROJs and push them with the same configuration and continue-on-error true.

**Comment by AraHaan** [comment]
I would rather do this instead:

```yml
    - name: Publish Release      
      id: publish_nuget
      uses: brandedoutcast/publish-nuget@master 
      with: 
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: **/*.csproj
        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: false
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        INCLUDE_SYMBOLS: false
```
