### ISSUE TITLE
[BUG] Unrecognized option '--skip-duplicate'

### ISSUE THREAD

**Issue by TheBeachMaster** [brandedoutcast/publish-nuget#51]
**Describe the bug**
This is somewhat similar to #37 . 

Given that #37 was closed with a link to [#4864](https://github.com/NuGet/Home/issues/4864) and commit [c12b854
](https://github.com/brandedoutcast/publish-nuget/commit/c12b8546b67672ee38ac87bea491ac94a587f7cc)

I have still encountered this issue trying to publish to Nuget with the following error

```
Generated Package(s): AfricasTalking.NET.1.2.1.nupkg
executing: [dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k *** --skip-duplicate -n 1]
Specify --help for a list of available options and commands.
error: Unrecognized option '--skip-duplicate
```

**Failed Action Log URL (Required)**
[https://github.com/AfricasTalkingLtd/africastalking.Net/actions/runs/342255796](https://github.com/AfricasTalkingLtd/africastalking.Net/actions/runs/342255796)

**To Reproduce**
1. In your `workflows/steps.yml` add the following
```yaml
name: .NETBuild

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '2.2.103', '3.0', '3.1.x' ]
    name: Build ${{ matrix.dotnet }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish Package
      uses: rohith/publish-nuget@v2
      with:
          PROJECT_FILE_PATH: AfricasTalkingCS/AfricasTalkingCS.csproj  ## Change to something else
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} ## Change to something else
          PACKAGE_NAME: AfricasTalking.NET ## Change to something else
```

**Expected Behavior**
Successful push to Nuget like [https://github.com/AfricasTalkingLtd/africastalking.Net/actions/runs/184718535](https://github.com/AfricasTalkingLtd/africastalking.Net/actions/runs/184718535)

**Environment:**
 - Platform : CI
 - Action Version [rohith/publish-nuget@v2](https://github.com/brandedoutcast/publish-nuget/blob/108c10b32aa03efa5f71af6a233dc2e8e32845cb/README.md)
