### ISSUE TITLE
[BUG] nuget push error

### ISSUE THREAD

**Issue by narojay** [brandedoutcast/publish-nuget#70]
[errormessage](https://github.com/narojay/Narojay.Tools.Core/runs/3601249643?check_suite_focus=true)

this is my yml ：

```yml
name: Publish Packages

on: [push]
  
jobs:
  build:
  
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ./
    - name: Pack with dotnet
      run: dotnet pack ./Narojay.Tools.Core.csproj --output nuget-packages --configuration Release
    - name: Run ls
      run: ls 
    - name: Push with dotnet
      run: dotnet nuget push ./nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json

```
i dont  know why always display this :
![image](https://user-images.githubusercontent.com/19280886/133297705-f2c83a73-cc41-4860-9bd5-3439648ffc75.png)
