### ISSUE TITLE
[BUG] It doesn't publish the package to nuget!

### ISSUE THREAD

**Issue by imaxs** [brandedoutcast/publish-nuget#75]
I am trying to publish a package to nuget using this:

```
name: Publish to Nuget

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install wkthtmltopdf
      run: |
        sudo apt-get install -y xfonts-base xfonts-75dpi
        wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
        sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101
    - name: Install dependencies
      run: dotnet restore HTMLconvert.sln
    - name: Build
      run: dotnet build HTMLconvert.sln --configuration Release --no-restore 
    - name: Tests
      run: dotnet test Tests/Tests.csproj
    - name: Publish HTMLconvert
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          NUGET_KEY: ${{secrets.NUGETKEY}}
          PROJECT_FILE_PATH: HTMLconvert/HTMLconvert.csproj
          VERSION_REGEX: <Version>(.*)<
```

Action completed successfully:

![[alt text](https://i.ibb.co/FmF4QKG/324324.png)](https://i.ibb.co/0mxy0cP/324324.png)

But the package has not been published.
